# Generated by Django 3.0.5 on 2020-05-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados_cadastrais',
            name='nome',
        ),
    ]
