# Generated by Django 3.0.7 on 2020-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0002_auto_20200619_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento',
            name='comercio',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='servico',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
