# Generated by Django 3.0.5 on 2020-05-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0003_auto_20200528_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Cadastrais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Dados_Cadastrais',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
