# Generated by Django 3.0.7 on 2020-06-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0004_auto_20200619_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento',
            name='seg_area',
            field=models.CharField(choices=[('AE', 'Aeronáutico/Aeroespacial'), ('AG', 'Agronécio')], default='', max_length=6),
            preserve_default=False,
        ),
    ]
