# Generated by Django 3.0.7 on 2020-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0005_dados_mapeamento_seg_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_mapeamento',
            name='seg_area',
            field=models.CharField(choices=[['AE', 'Aeronáutico/Aeroespacial'], ['AG', 'Agronécio']], max_length=6),
        ),
    ]
