# Generated by Django 3.0.6 on 2020-06-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0007_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereco'},
        ),
    ]
