# Generated by Django 3.0.7 on 2020-06-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0008_auto_20200619_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_mapeamento',
            old_name='area_atu',
            new_name='area_de_atuacao_da_empresa_ou_startup',
        ),
        migrations.RenameField(
            model_name='dados_mapeamento',
            old_name='detalhes_area',
            new_name='detalhes_de_area_de_atuacao',
        ),
        migrations.RenameField(
            model_name='dados_mapeamento',
            old_name='seg_atuacao',
            new_name='seg_de_atuacao',
        ),
        migrations.RenameField(
            model_name='dados_mapeamento',
            old_name='seg_area',
            new_name='segmento_area',
        ),
    ]
