# Generated by Django 3.0.7 on 2020-06-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0009_auto_20200619_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_mapeamento',
            old_name='seg_de_atuacao',
            new_name='segmento_de_atuacao',
        ),
    ]
