# Generated by Django 3.0.7 on 2020-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0010_auto_20200619_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento',
            name='tipo_de_cliente',
            field=models.CharField(choices=[('B2B', 'Empresas e Negócios'), ('B2C', 'Consumidores'), ('GOV', 'Governo')], default='', max_length=6),
            preserve_default=False,
        ),
    ]
