# Generated by Django 3.0.7 on 2020-06-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0013_auto_20200619_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_mapeamento',
            name='possui_mercado_Global',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')]),
        ),
    ]
