# Generated by Django 3.0.7 on 2020-06-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0015_auto_20200620_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados_mapeamento',
            name='comercio',
        ),
        migrations.RemoveField(
            model_name='dados_mapeamento',
            name='industria',
        ),
        migrations.RemoveField(
            model_name='dados_mapeamento',
            name='servico',
        ),
    ]
