# Generated by Django 3.0.7 on 2020-06-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0027_auto_20200620_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento',
            name='qual_estrategia_de_saida_ou_idealizada_para_o_negocio',
            field=models.CharField(choices=[('cre', 'Crescimento Lucrativo para o Mercado Global '), ('aqu', 'Aquisição por uma Grande Empresa'), ('fus', 'Fusão com outra empresa'), ('ofe', 'Oferta Pública Inicial de Ações')], default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='dados_mapeamento',
            name='tipo_de_cliente',
            field=models.CharField(choices=[('B2B', 'Empresas e Negócios (B2B) '), ('B2C', 'Consumidores (B2C) '), ('GOV', 'Governo')], default=0, max_length=6),
        ),
    ]
