# Generated by Django 3.0.7 on 2020-06-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0029_auto_20200620_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_mapeamento',
            name='qual_estrategia_de_saida_ou_idealizada_para_o_negocio',
            field=models.CharField(choices=[('cre', 'Crescimento Lucrativo para o Mercado Global '), ('aqu', 'Aquisição por uma Grande Empresa'), ('fus', 'Fusão com outra empresa'), ('ofe', 'Oferta Pública Inicial de Ações')], default=0, max_length=6),
        ),
    ]
