# Generated by Django 3.0.7 on 2020-06-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0031_remove_dados_mapeamento_qual_estrategia_de_saida_ou_idealizada_para_o_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_mapeamento',
            name='setor_de_atuacao',
            field=models.CharField(choices=[(True, 'Indústria'), (True, 'Comércio'), (True, 'Serviços')], default=0, max_length=6),
        ),
    ]
