# Generated by Django 3.0.7 on 2020-06-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0033_auto_20200620_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_mapeamento',
            name='setor_de_atuacao',
            field=models.BooleanField(choices=[('ind', 'Indústria'), ('com', 'Comércio'), ('ser', 'Serviços')], default=0),
        ),
    ]
