# Generated by Django 3.0.7 on 2020-06-20 22:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0044_auto_20200620_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento',
            name='qual_estrategia_de_saida_ou_idealizada_para_o_negocio',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cre', 'Crescimento Lucrativo para o Mercado Global '), ('aqu', 'Aquisição por uma Grande Empresa'), ('fus', 'Fusão com outra empresa'), ('ofe', 'Oferta Pública Inicial de Ações')], default=0, max_length=15),
        ),
    ]
