# Generated by Django 3.0.7 on 2020-06-20 22:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0045_dados_mapeamento_qual_estrategia_de_saida_ou_idealizada_para_o_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_mapeamento',
            name='possui_mercado_Global',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(True, 'Sim'), (False, 'Não')], default=3, max_length=10),
        ),
    ]
