# Generated by Django 3.0.7 on 2020-06-20 22:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0047_auto_20200620_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento',
            name='caso_outra',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='sua_startup_possui_conhecimento_ou_e_treinada_nas_metodologias_descritas_abaixo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lsu', 'Lean Startt up '), ('mod', 'Modelo de Negócios'), ('des', 'Designer Thinking'), ('out', 'Outras ?')], default=0, max_length=15),
        ),
    ]
