# Generated by Django 3.0.7 on 2020-06-20 23:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0051_auto_20200620_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento',
            name='ano_de_fundacao',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='com_quais_entidades_do_ecossistema_tem_conexao_interacao_frequente_projetos_em_parceria_colaboracao_que_contribuiram_e_contribuem_para_as_inovacoes_e_aperfeicoamento_da_empresa',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='estes_parceiros_listados_acima_possuem_que_esfera',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('reg', 'Regional'), ('est', 'Estadual'), ('nac', 'Nacional'), ('int', 'Internacional')], default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='ja_foi_investida',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=0),
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='montante_investido',
            field=models.CharField(default='', max_length=1000000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='numero_de_socios',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='quais_os_modelos_de_receitas_se_enquadra_no_perfil_da_empresa_startup',
            field=models.CharField(choices=[['Ven', 'Venda Unitária (Produto)'], ['Ven', 'Venda Direta'], ['Ven', 'Venda Indireta (agentes ou representantes)'], ['Fre', 'Freemium'], ['Sof', 'Software as a service (SaaS)'], ['Rec', 'Receita com anúncios'], ['Lic', 'Licença por usuário'], ['Lic', 'Licença por produto'], ['Suc', 'Sucessfee'], ['Hom', 'Homem hora'], ['Com', 'Comissão'], ['Mar', 'Markup'], ['Oth', 'Other']], default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='quais_programas_iniciativas_movimentos_de_empreendedorismo_e_inovacao_que_participa',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_mapeamento',
            name='quantas_rodadas',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dados_mapeamento',
            name='possui_Influencia_ou_interesse_militar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=0),
        ),
    ]
