# Generated by Django 3.1.4 on 2020-12-15 19:34

from django.db import migrations, models
import localflavor.br.models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0054_auto_20201215_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='cargo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='em_qual_destes_itens_abaixo_seu_cadastro_se_enquadrada',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('aca', 'Academia(inst. de Nível Técnico ou Superior'), ('empre', 'Empresa'), ('soc', 'Sociedade'), ('gov', 'Governo')], default=0, max_length=17),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='email_representante',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='estado',
            field=localflavor.br.models.BRStateField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='BigV_app_map/static/media_root'),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='nome_representante',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='rua',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='site',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='dados_mapeamento_startup',
            name='tipo_de_cliente',
            field=models.CharField(choices=[('B2B', 'Empresas e Negócios (B2B) '), ('B2C', 'Consumidores (B2C)'), ('GOV', 'Governo')], default='', max_length=100),
        ),
    ]
