# Generated by Django 3.1.4 on 2020-12-16 00:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0056_auto_20201215_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_mapeamento_empresa',
            name='em_qual_destes_itens_abaixo_seu_cadastro_se_enquadrada',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('aca', 'Academia (inst. de Nível Técnico ou Superior)'), ('empre', 'Empresa'), ('soc', 'Sociedade'), ('gov', 'Governo')], default=0, max_length=17),
        ),
    ]
