# Generated by Django 3.1.4 on 2020-12-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0058_auto_20201215_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='equipamentos_disponiveis_para_uso_compartilhado_prestacao_de_servico_no_Ecossistema_Regional',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='programas_iniciativas_movimentos_de_empreendedorismo_e_inovacao_que_executa',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='programas_iniciativas_movimentos_de_empreendedorismo_e_inovacao_que_participa',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
