# Generated by Django 3.1.4 on 2020-12-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0059_auto_20201215_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='referente_a_capital_humano',
            field=models.CharField(blank=True, choices=[['Org', 'Organizações Integrativas'], ['Ser', 'Serviços de Suporte a Negócios e ao Ecossistema'], ['Coa', 'Coaches'], ['Con', 'Consultores'], ['Ace', 'Acessores'], ['Men', 'Mentores']], default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='segmento',
            field=models.CharField(choices=[['Aer', 'Aeronáutico'], ['Agr', 'Agronégocio'], ['Arq', 'Arquitetura e Design'], ['Aut', 'Automotivo'], ['Bel', 'Beleza'], ['Bio', 'Biotecnologia'], ['Com', 'Comida e Bebida'], ['Con', 'Construção Civil'], ['Edu', 'Educação'], ['Far', 'Farmacêutico'], ['Ges', 'Gestão de Resíduos'], ['Mat', 'Matérias Primas e Químicos'], ['Mod', 'Moda e Textil'], ['Mid', 'Midia'], ['Saú', 'Saúde e Bem-estar'], ['Ser', 'Serviço'], ['Tec', 'Tech: TI e Software'], ['Tec', 'Tech: Hardware e Equipamentos'], ['Tec', 'Tech: Mobile'], ['Tel', 'Telecomunicações'], ['Var', 'Varejo'], ['Naú', 'Naútico'], ['Nav', 'Naval'], ['Art', 'Arte e Cultura'], ['Tur', 'Turismo']], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='sobre_referencia_politica',
            field=models.CharField(blank=True, choices=[('gov', 'Gorverno'), ('out', 'Outras Lideranças Política')], default='', max_length=100, null=True),
        ),
    ]
