# Generated by Django 3.1.4 on 2020-12-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0060_auto_20201217_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_mapeamento_empresa',
            name='em_qual_destes_setores_a_instituicao_se_enquadra',
            field=models.CharField(choices=[('pol', 'Política'), ('cul', 'Cultura'), ('ch', 'Capital Humano'), ('fin', 'Financeiro'), ('sup', 'Suporte'), ('merc', 'Mercado')], max_length=100, null=True),
        ),
    ]
