# Generated by Django 3.1.4 on 2020-12-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0061_auto_20201217_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='referente_a_cultura',
            field=models.CharField(blank=True, choices=[('cul', 'Cultura / Valores Sociais e Empreendedores')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dados_mapeamento_empresa',
            name='referente_a_capital_humano',
            field=models.CharField(blank=True, choices=[['Emp', 'Empreendedores'], ['Esp', 'Especialistas - Talentos Técnicos e Criativos'], ['Pro', 'Professores / Pesquisadores'], ['Inv', 'Inventores'], ['Aca', 'Academia / Curso Técnico e Graduação']], max_length=100, null=True),
        ),
    ]
