# Generated by Django 3.1.4 on 2020-12-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0062_auto_20201218_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='referente_a_financeiro',
            field=models.CharField(blank=True, choices=[('fin', 'Capital')], max_length=100, null=True),
        ),
    ]
