# Generated by Django 3.1.4 on 2020-12-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0063_dados_mapeamento_empresa_referente_a_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_mapeamento_empresa',
            name='referente_a_suporte',
            field=models.CharField(blank=True, choices=[['Org', 'Organizações Integrativas'], ['Ser', 'Serviços de Suporte a Negócios e ao Ecossistema'], ['Coa', 'Coaches'], ['Con', 'Consultores'], ['Ace', 'Acessores'], ['Men', 'Mentores']], max_length=100, null=True),
        ),
    ]
