# Generated by Django 3.1.4 on 2020-12-19 03:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BigV_app_map', '0065_auto_20201219_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_mapeamento_startup',
            name='email_representante',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='dados_mapeamento_startup',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+BR', max_length=128, region=None),
        ),
    ]
